# Generated by Django 5.2.4 on 2025-07-15 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Signal Timestamp')),
                ('timeframe', models.CharField(default='1h', max_length=5, verbose_name='Timeframe')),
                ('signal_type', models.CharField(max_length=100, verbose_name='Signal Type')),
                ('price_at_signal', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Price at Signal')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Stores the full JSON output from the analysis engine.', verbose_name='Analysis Details')),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('archived', 'Archived')], db_index=True, default='new', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Entry Price')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Exit Price')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Stop Loss')),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Take Profit')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('canceled', 'Canceled')], db_index=True, default='open', max_length=10, verbose_name='Status')),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Profit/Loss ($)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Opened At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.signal', verbose_name='Associated Signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-opened_at'],
            },
        ),
    ]
