# nixpacks.toml (نسخه قطعی با تعریف محیط کامل)

[phases.setup]
# ما یک محیط کامل را با تمام نیازمندی‌های پروژه خود تعریف می‌کنیم:
# python311: مفسر پایتون نسخه ۳.۱۱ (یک نسخه مدرن و پایدار)
# gcc: کامپایلر GNU C/C++ که برای ساخت پکیج‌های پایتون لازم است
# ta-lib: کتابخانه C برای TA-Lib
# pkg-config: ابزار کمکی برای پیدا کردن کتابخانه‌ها توسط کامپایلر
nixPkgs = ["python311", "gcc", "ta-lib", "pkg-config"]

[start]
# مشخص می‌کنیم که برنامه اصلی ما (وب سرور Django) چگونه باید اجرا شود.
# ما از Gunicorn استفاده می‌کنیم که استاندارد صنعتی برای اجرای جنگو در محیط پروداکشن است.
# همچنین به Nixpacks می‌گوییم که از پایتون ۳.۱۱ برای اجرای Gunicorn استفاده کند.
cmd = "python311 -m gunicorn trading_app.wsgi"
