# nixpacks.toml (نسخه نهایی با استفاده از پکیج منیجر Nix)

[phases.setup]
# به جای apt-get و دستورات پیچیده، فقط نام پکیج‌ها را به Nix می‌دهیم.
# خود Nix بهترین نسخه از ta-lib و ابزارهای لازم مانند pkg-config را پیدا و نصب می‌کند.
nixPkgs = ["ta-lib", "pkg-config"]
