# Generated by Django 5.0.7 on 2025-08-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='e.g., BTC/USDT', max_length=20)),
                ('timeframe', models.CharField(db_index=True, help_text='e.g., 1h', max_length=5)),
                ('status', models.CharField(help_text='SUCCESS or NEUTRAL', max_length=10)),
                ('full_analysis', models.JSONField(default=dict, help_text='The full analysis summary from IndicatorAnalyzer')),
                ('signal_package', models.JSONField(blank=True, default=dict, help_text='The complete signal package if status is SUCCESS', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis Snapshot',
                'verbose_name_plural': 'Analysis Snapshots',
                'ordering': ['-last_updated'],
                'unique_together': {('symbol', 'timeframe')},
            },
        ),
    ]
